#!/usr/bin/env python3
"""Write app/static/sounds/bank.json and docs/SOUND-ATTRIBUTION.md.

The bank has two provenances and the manifest records which is which:
files scraped from Wikimedia Commons under a permissive licence, and files
synthesised by tools/make_sounds.py (original, CC0).
"""
import json
import os
import sys

RAW = "app/static/sounds/_raw"
OUT = "app/static/sounds"

# Labels for the synthesised half are taken straight from the synthesiser, so
# the two cannot drift apart.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_sounds import GENERATED, MEMORY            # noqa: E402

SYNTH = {slug: (en, fr) for slug, en, fr, _fn in GENERATED + MEMORY}

SCRAPED_LABELS = {
    "bell":    ("Bell", "Cloche"),
    "thunder": ("Thunder", "Tonnerre"),
    "waves":   ("Waves", "Vagues"),
}

# Roughly grouped: weather, nature, home, machines. The categories were left
# open on purpose -- participants decide what matters -- so this is only a
# sensible reading order, not a taxonomy.
ORDER = [
    # weather and water
    "rain", "rainwindow", "wind", "waves", "thunder",
    # outdoors
    "birds", "seagulls", "crickets", "fire", "snowsteps", "water",
    # the house
    "clock", "metronome", "kettle", "spoon", "door", "floor",
    # machines and instruments
    "telephone", "typewriter", "radio", "sewing", "musicbox", "organ",
    "engine", "boat", "train", "whistle",
    # bells and body
    "bell", "chime", "heartbeat",
]


def main():
    scraped = {}
    manifest_path = os.path.join(RAW, "manifest.json")
    if os.path.exists(manifest_path):
        with open(manifest_path) as fh:
            for row in json.load(fh):
                scraped[row["slug"]] = row

    bank, credits = [], []
    for slug in ORDER:
        mp3 = os.path.join(OUT, f"{slug}.mp3")
        if not os.path.exists(mp3):
            print(f"  ! missing {mp3}, skipping")
            continue
        if slug in scraped:
            row = scraped[slug]
            label_en, label_fr = SCRAPED_LABELS.get(slug, (slug.title(), slug.title()))
            entry = {
                "slug": slug, "label_en": label_en, "label_fr": label_fr,
                "url": f"/static/sounds/{slug}.mp3",
                "licence": row["licence"], "source": "Wikimedia Commons",
            }
            credits.append((label_en, row["licence"], row["author"], row["page"], row["title"]))
        else:
            label_en, label_fr = SYNTH.get(slug, (slug.title(), slug.title()))
            entry = {
                "slug": slug, "label_en": label_en, "label_fr": label_fr,
                "url": f"/static/sounds/{slug}.mp3",
                "licence": "CC0", "source": "synthesised",
            }
        entry["bytes"] = os.path.getsize(mp3)
        bank.append(entry)

    with open(os.path.join(OUT, "bank.json"), "w") as fh:
        json.dump(bank, fh, indent=2, ensure_ascii=False)

    lines = [
        "# Sound bank attribution", "",
        "The built-in sounds in `app/static/sounds/` come from two places.", "",
        "## Synthesised (CC0)", "",
        "Generated by `tools/make_sounds.py` -- filtered noise and oscillators, no",
        "recordings involved. Original work, dedicated to the public domain under CC0.", "",
    ]
    for entry in bank:
        if entry["source"] == "synthesised":
            lines.append(f"- **{entry['label_en']}** (`{entry['slug']}.mp3`)")
    lines += ["", "## From Wikimedia Commons", "",
              "Fetched by `tools/fetch_sounds.py`, which accepts only CC0, public-domain",
              "and CC BY files. Each remains under its own licence.", ""]
    for label, licence, author, page, title in credits:
        lines.append(f"- **{label}** -- {title}")
        lines.append(f"  - Licence: {licence}")
        lines.append(f"  - Author: {author}")
        if page:
            lines.append(f"  - Source: {page}")
    lines += ["", "All files were transcoded to mono MP3 and trimmed to 8 seconds by",
              "`tools/convert_sounds.sh`; the originals are not redistributed here.", ""]

    os.makedirs("docs", exist_ok=True)
    with open("docs/SOUND-ATTRIBUTION.md", "w") as fh:
        fh.write("\n".join(lines))

    total = sum(e["bytes"] for e in bank)
    print(f"  {len(bank)} sounds, {total // 1024}KB total")
    for e in bank:
        print(f"    {e['slug']:10} {e['label_fr']:14} {e['licence']:14} {e['source']}")


if __name__ == "__main__":
    sys.exit(main())
